# Generated by Django 5.2 on 2025-04-16 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='메시지 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
            ],
            options={
                'verbose_name': '메시지',
                'verbose_name_plural': '메시지 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
